# Generated by Django 5.1 on 2024-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0004_alter_createevent_img'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup'),
        ),
    ]
